name: test
on:
- pull_request
jobs:
  xenial:
    container: 
      image: vapor/swift:5.1-xenial
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        POSTGRES_HOSTNAME: psql
  bionic:
    container: 
      image: vapor/swift:5.1-bionic
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        POSTGRES_HOSTNAME: psql
  fluent:
    container: 
      image: vapor/swift:5.1
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    steps:
    - run: git clone -b master https://github.com/vapor/fluent-postgres-driver.git
      working-directory: ./
    - run: swift package edit postgres-nio --revision ${{ github.sha }}
      working-directory: ./fluent-postgres-driver
    - run: swift test --enable-test-discovery --sanitize=thread
      working-directory: ./fluent-postgres-driver
      env:
        POSTGRES_HOSTNAME: psql
  mojave:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - run: swift test --sanitize=thread
      env:
        POSTGRES_HOSTNAME: ec2-107-21-93-51.compute-1.amazonaws.com
        POSTGRES_USERNAME: yziezjbdbxmxlv
        POSTGRES_PASSWORD: f790ba67d1b28636aac979364d4e21bfa9345fa1029ddf5884c74a8fb5821894
        POSTGRES_DATABASE: dc0l7louij2ltv
        POSTGRES_TLS: true
  ios:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - run: xcodebuild test -destination 'name=iPhone 11' -scheme 'postgres-nio'
      env:
        POSTGRES_HOSTNAME: ec2-107-21-93-51.compute-1.amazonaws.com
        POSTGRES_USERNAME: yziezjbdbxmxlv
        POSTGRES_PASSWORD: f790ba67d1b28636aac979364d4e21bfa9345fa1029ddf5884c74a8fb5821894
        POSTGRES_DATABASE: dc0l7louij2ltv
        POSTGRES_TLS: true
